// config/permissions.js — Single source of truth for all role permissions
module.exports = {
  owner: {
    'dashboard:view':true,'stores:view':true,'stores:create':true,'stores:edit':true,'stores:delete':true,
    'orders:view':true,'orders:export':true,'orders:send_wa':true,
    'conversations:view':true,'conversations:reply':true,'conversations:assign':true,
    'flows:view':true,'flows:create':true,'flows:edit':true,'flows:delete':true,'flows:toggle':true,
    'templates:view':true,'templates:create':true,'templates:edit':true,'templates:delete':true,
    'catalogue:view':true,'catalogue:create':true,'catalogue:edit':true,'catalogue:delete':true,'catalogue:sync':true,
    'broadcasts:view':true,'broadcasts:create':true,'broadcasts:send':true,'broadcasts:delete':true,
    'analytics:view':true,'analytics:export':true,
    'billing:view':true,'billing:manage':true,
    'settings:view':true,'settings:edit':true,
    'team:view':true,'team:invite':true,'team:edit':true,'team:remove':true,
    'whatsapp:view':true,'whatsapp:setup':true,'whatsapp:manage':true,
  },
  admin: {
    'dashboard:view':true,'stores:view':true,'stores:create':true,'stores:edit':true,'stores:delete':false,
    'orders:view':true,'orders:export':true,'orders:send_wa':true,
    'conversations:view':true,'conversations:reply':true,'conversations:assign':true,
    'flows:view':true,'flows:create':true,'flows:edit':true,'flows:delete':false,'flows:toggle':true,
    'templates:view':true,'templates:create':true,'templates:edit':true,'templates:delete':false,
    'catalogue:view':true,'catalogue:create':true,'catalogue:edit':true,'catalogue:delete':false,'catalogue:sync':true,
    'broadcasts:view':true,'broadcasts:create':true,'broadcasts:send':true,'broadcasts:delete':false,
    'analytics:view':true,'analytics:export':true,
    'billing:view':true,'billing:manage':false,
    'settings:view':true,'settings:edit':true,
    'team:view':true,'team:invite':true,'team:edit':false,'team:remove':false,
    'whatsapp:view':true,'whatsapp:setup':false,'whatsapp:manage':false,
  },
  marketing: {
    'dashboard:view':true,'stores:view':true,'stores:create':false,'stores:edit':false,'stores:delete':false,
    'orders:view':false,'orders:export':false,'orders:send_wa':false,
    'conversations:view':true,'conversations:reply':false,'conversations:assign':false,
    'flows:view':true,'flows:create':true,'flows:edit':true,'flows:delete':false,'flows:toggle':false,
    'templates:view':true,'templates:create':true,'templates:edit':true,'templates:delete':false,
    'catalogue:view':true,'catalogue:create':true,'catalogue:edit':true,'catalogue:delete':false,'catalogue:sync':true,
    'broadcasts:view':true,'broadcasts:create':true,'broadcasts:send':true,'broadcasts:delete':false,
    'analytics:view':true,'analytics:export':true,
    'billing:view':false,'billing:manage':false,
    'settings:view':false,'settings:edit':false,
    'team:view':false,'team:invite':false,'team:edit':false,'team:remove':false,
    'whatsapp:view':false,'whatsapp:setup':false,'whatsapp:manage':false,
  },
  sales: {
    'dashboard:view':true,'stores:view':true,'stores:create':false,'stores:edit':false,'stores:delete':false,
    'orders:view':true,'orders:export':true,'orders:send_wa':true,
    'conversations:view':true,'conversations:reply':true,'conversations:assign':false,
    'flows:view':true,'flows:create':false,'flows:edit':false,'flows:delete':false,'flows:toggle':false,
    'templates:view':true,'templates:create':false,'templates:edit':false,'templates:delete':false,
    'catalogue:view':true,'catalogue:create':false,'catalogue:edit':false,'catalogue:delete':false,'catalogue:sync':false,
    'broadcasts:view':true,'broadcasts:create':false,'broadcasts:send':false,'broadcasts:delete':false,
    'analytics:view':true,'analytics:export':false,
    'billing:view':false,'billing:manage':false,
    'settings:view':false,'settings:edit':false,
    'team:view':false,'team:invite':false,'team:edit':false,'team:remove':false,
    'whatsapp:view':false,'whatsapp:setup':false,'whatsapp:manage':false,
  },
  support: {
    'dashboard:view':true,'stores:view':true,'stores:create':false,'stores:edit':false,'stores:delete':false,
    'orders:view':true,'orders:export':false,'orders:send_wa':true,
    'conversations:view':true,'conversations:reply':true,'conversations:assign':true,
    'flows:view':true,'flows:create':false,'flows:edit':false,'flows:delete':false,'flows:toggle':false,
    'templates:view':true,'templates:create':false,'templates:edit':false,'templates:delete':false,
    'catalogue:view':true,'catalogue:create':false,'catalogue:edit':false,'catalogue:delete':false,'catalogue:sync':false,
    'broadcasts:view':false,'broadcasts:create':false,'broadcasts:send':false,'broadcasts:delete':false,
    'analytics:view':false,'analytics:export':false,
    'billing:view':false,'billing:manage':false,
    'settings:view':false,'settings:edit':false,
    'team:view':false,'team:invite':false,'team:edit':false,'team:remove':false,
    'whatsapp:view':false,'whatsapp:setup':false,'whatsapp:manage':false,
  },
};
